# Generated by Django 2.1.4 on 2018-12-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_user', '0002_auto_20181212_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faresuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
