# Generated by Django 2.1.4 on 2018-12-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_jadwal', '0002_auto_20181214_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtteamteaching',
            name='teacherId',
        ),
        migrations.AddField(
            model_name='dtteamteaching',
            name='faresUserId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
