# Generated by Django 2.1.4 on 2018-12-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_jadwal', '0004_auto_20181214_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamteaching',
            name='deptId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
        ),
    ]
