# Generated by Django 2.1.4 on 2018-12-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_jadwal', '0005_auto_20181214_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtteamteaching',
            name='teamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_jadwal.teamTeaching'),
        ),
    ]
