# Generated by Django 2.1.4 on 2018-12-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_jadwal', '0006_auto_20181214_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_offer',
            name='subjectOfferId',
        ),
    ]
