# Generated by Django 2.1.4 on 2018-12-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_jadwal', '0007_remove_subject_offer_subjectofferid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_offer',
            name='classRoomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.classRoom'),
        ),
        migrations.AlterField(
            model_name='subject_offer',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
        ),
        migrations.AlterField(
            model_name='subject_offer',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.subject'),
        ),
        migrations.AlterField(
            model_name='subject_offer',
            name='teamTeaching_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_jadwal.teamTeaching'),
        ),
        migrations.AlterField(
            model_name='subject_offer',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_jadwal.time'),
        ),
    ]
