# Generated by Django 2.1.4 on 2018-12-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_jadwal', '0010_auto_20181229_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtteamteaching',
            name='faresUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dtteamteaching',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_jadwal.teamTeaching'),
        ),
    ]
