# Generated by Django 2.1.4 on 2018-12-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_registred_no', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('photo', models.TextField()),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)])),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement')),
            ],
        ),
        migrations.CreateModel(
            name='studentFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_function', models.TextField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.student')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50)),
                ('national_teacher_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.religion')),
            ],
        ),
        migrations.CreateModel(
            name='teacherFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_face', models.TextField()),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.unit'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
        ),
    ]
