# Generated by Django 2.1.4 on 2018-12-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
        ),
    ]
