# Generated by Django 2.1.4 on 2018-12-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_asset', '0003_auto_20181214_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
            preserve_default=False,
        ),
    ]
