# Generated by Django 2.1.4 on 2018-12-29 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_scheduling', '0002_auto_20181229_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='studentId',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
