# Generated by Django 2.1.4 on 2019-01-01 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_scheduling', '0003_auto_20181229_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='departementId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_asset.departement'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='studentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='subjectOfferId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_jadwal.subject_offer'),
        ),
    ]
